name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: gpt-4o-mini
          LANGUAGE: Russian
          PROMPT: >
            Проверь изменения в коде. Укажи ошибки, потенциальные баги,
            нарушения best practices, а также дай рекомендации по
            улучшению читаемости, производительности и безопасности.
          top_p: 1
          temperature: 0.5
          max_tokens: 4000
          MAX_PATCH_LENGTH: 30000
          IGNORE_PATTERNS: /node_modules/**/*,*.md
